@echo off
setlocal EnableExtensions
cd /d "%~dp0\.."

echo Validating deployed V6.8 public keys...
if not exist "desktop_app\resources\license_public_key.pem" (
  echo ERROR: Missing desktop_app\resources\license_public_key.pem
  echo Restore the matching V6.8 deployed PUBLIC key. Build will not generate a new trust chain.
  exit /b 1
)
if not exist "desktop_app\resources\update_public_key.pem" (
  echo ERROR: Missing desktop_app\resources\update_public_key.pem
  echo Restore the matching V6.8 deployed PUBLIC key. Build will not generate a new trust chain.
  exit /b 1
)

echo Public keys ready. Private keys are never required or generated by the desktop build.
exit /b 0
